### ISSUE TITLE
jQuery dependency

### ISSUE THREAD

**Issue by shacker** [alefeuvre/foundation-grid-displayer#1]
I see that grid-displayer include jquery.min.js . But when I click the bookmarklet on a dev site that does not include jquery, I get a popup error "The grid displayer requires jQuery + Bootstrap or Foundation." 

I am using Foundation, but we are using Angular and have no intention of adding jQuery to our site. Apparently, grid-displayer isn't finding the copy of jquery it comes bundled with (nor does it know how to load it from a CDN if it's missing).

Can this be handled more elegantly?

Thanks,
Scot

**Comment by alefeuvre** [comment]
Hey Scot,

I apologise it took me forever to answer.

The grid displayer doesn't come bundled with jQuery. I have jquery.min.js for the presentation website only.

I've had "load jQuery from a CDN" in my to-do list for quite a while. Time to take action! I keep you posted.

Thanks for your message

**Comment by alefeuvre** [comment]
Issue fixed by this commit c0f1f295292074b3b621d8225564871b053cb0e1
Code excerpt: https://github.com/alefeuvre/foundation-grid-displayer/blob/gh-pages/gd-bookmarklet.js#L176-183
