### ISSUE TITLE
Project separation?

### ISSUE THREAD

**Issue by pentago** [alefeuvre/foundation-grid-displayer#12]
Any chance we could get 2 separate bookmarklets? 

One for each, Foundation and Bootstrap (_each defaulting to the latest build_) to avoid selecting the one we use all the time?

Would be much more convenient for people who use only one of these projects exclusively.

**Comment by alefeuvre** [comment]
Hi,
Have you tried to set the parameters via data attributes https://snipt.net/jiraisurfer/custom-parameters-for-foundation-grid-displayer/ ? I'm not sure I want to split the bookmarklet, since developers working with the two front-end frameworks are probably happy to have a 2-in-1 tool.

-----Original Message-----
From: Goran
Sent: 07/04/2014 04:11
To: alefeuvre/foundation-grid-displayer
Subject: [foundation-grid-displayer] Project separation? (#12)

Any chance we could get 2 separate bookmarklets? 

One for each, Foundation and Bootstrap (each defaulting to the latest build) to avoid selecting the one we use all the time?

Would be much more convenient for people who use only one of these projects exclusively.

**Comment by pentago** [comment]
Hey, yeah i did but often i use the bookmarklet just to inspect some website and just want to fire the bookmarklet and check what i wanted without having to choose framework i prefer each time. I find it somewhat annoying even though i realize that someone could prefer it that way.

Also, i  think that people who do frontend stuff tend to stick to only one framework at a time and even if they don't, text is cheap so having two separate bookmarklets totally wouldn't be the issue for anyone. 

Nobody uses both Foundation and Bootstrap on same site, right? When you work on Foundation site, you use Foundation bookmarklet, when you work on Bootstrap site, you use Bootstrap bookmarklet.

It would be immensely more convenient to get the wanted grid right away instead of having to choose preferred one each time. Also, one could assign key shortcuts to individual bookmarklets instead of having to click for it.

Of course, this is just my opinion, it doesn't necessarily have to be the right one.
As an alternative, would you consider making bookmarklets separate in addition to current, unified one. That way people would have even more choice. Also, it would be much easier for maintaining.

Thoughts?

**Comment by alefeuvre** [comment]
Hi Goran,

I see your point, it makes sense. Yet, it still believe splitting the 
bookmarklet is a 'destructive' solution. I reckon a smarter option would 
be automatic framework detection. I thought about it a while ago, but 
never had the chance to research it and verify whether it was feasible.

What do you think?
Other developers, any thoughts on this?

**Comment by alefeuvre** [comment]
Hi Goran,
I've finally taken some time to look into automatic framework detection. I'm unhappy with the results, not reliable enough. Therefore I decided to implement the separation you suggested. Version 3.2 released last week comes with Bootstrap only and Foundation only options. The bookmarklet has to be re-added to get these new options. Go to http://alefeuvre.github.io/foundation-grid-displayer/, you'll see the custom 'install' is very easy to use.
I hope it helps! Thank you for suggesting this feature.

**Comment by pentago** [comment]
Great mate. Maybe just making these split bookmarklets default to latest versions instead oldest. That would be much more convenient. 

Cheers

**Comment by alefeuvre** [comment]
It does default to the latest version (i.e. Bootstrap 3). Have you noticed a different behaviour? Which browser have you used?

**Comment by pentago** [comment]
Yes, you're right. I opened your site i think and tried bookmarklet. You'e using some older build of Foundation so that confused me. Disregard this, its all good :+1:

**Comment by alefeuvre** [comment]
Perfect! (Yes, on my site, I use a data attribute to set the framework as Foundation 2.)

-----Original Message-----
