### ISSUE TITLE
Foundation 4

### ISSUE THREAD

**Issue by pboling** [alefeuvre/foundation-grid-displayer#3]
[F4 changed the classes for the grid](http://foundation.zurb.com/migration.php).  I may take a stab at a pull request to add this.

**Comment by alefeuvre** [comment]
Hi Peter,

Thank you for your message and sorry it took me months to reply.

You're right, F4 support is a much needed improvement. I'll have a look into it in the next few days. Unless you tell me you want to go ahead with your PR!

I keep you informed

**Comment by alefeuvre** [comment]
There you go, Foundation 4 is now supported c0356d4b491a1288ac150aa9c2bc8d5825b069e5. I've tested it on several sites, including these two http://www.wndrmnt.com and http://pg.lacrema.com.
It only supports the large grid (from 768px) for the time being.

**Comment by pboling** [comment]
That's awesome!  Thanks! :+1:

**Comment by alefeuvre** [comment]
You're welcome Peter. I'm glad you like it!
