### ISSUE TITLE
Bootstrap 3 support

### ISSUE THREAD

**Issue by thorsten** [alefeuvre/foundation-grid-displayer#6]
Please add Bootstrap 3 support as it'll soon "ready" :-) Thanks!

**Comment by alefeuvre** [comment]
Thanks Thorsten. I'll definitely add Bootstrap 3 support once the master is released. Stay tuned!

**Comment by thorsten** [comment]
Thanks, looking foward for the new release! :-)

**Comment by thorsten** [comment]
Please check https://github.com/alefeuvre/foundation-grid-displayer/pull/7
